export const apiUrls = {
  Authentication: {
    SignIn: 'Auth/login',
    SignUp: 'Auth/signup',
    findEmail: 'Auth/findEmail',
    changepassword: 'Auth/changepassword',
  },
  Business: {
    AddMovie: 'Admin/AddMovie',
    UpdateMovie: 'Admin/UpdateMovie',
    GetMovie: 'Admin/GetMovie',
    DeleteMovie: 'Admin/DeleteMovie',
    GetMovieById: 'Admin/GetMovieById',
    GetBookingList: 'Admin/GetBookingList',
    GetReviewList: 'Admin/GetReviewList',
    AddTheater:"Admin/AddTheater",
    UpdateTheater:"Admin/UpdateTheater",
    GetTheater:"Admin/GetTheater",
    DeleteTheater:"Admin/DeleteTheater",
  },
  Service: {
    AddProfile: 'User/AddProfile',
    UpdateProfile: 'User/UpdateProfile',
    GetProfile: 'User/GetProfile',
    AddBooking: 'User/AddBooking',
    GetBooking: 'User/GetBooking',
    GetBookingByUserId: 'User/GetBookingByUserId',
    UpdateBooking: 'User/UpdateBooking',
    AddReview: 'User/AddReview',
    UpdateReview: 'User/UpdateReview',
    GetReviewByMovieId: 'User/GetReviewByMovieId',
    DeleteReview: 'User/DeleteReview',
    SearchMovie: 'User/SearchMovie',
    SearchMovieBycategory: 'User/SearchMovieBycategory',
  },
};
